# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(755, 508)
        self.label_image_1 = QtWidgets.QLabel(Form)
        self.label_image_1.setGeometry(QtCore.QRect(270, 20, 450, 451))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_1.setFont(font)
        self.label_image_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_1.setScaledContents(False)
        self.label_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_1.setObjectName("label_image_1")
        self.pushButton_open_image = QtWidgets.QPushButton(Form)
        self.pushButton_open_image.setGeometry(QtCore.QRect(90, 40, 111, 28))
        self.pushButton_open_image.setCheckable(False)
        self.pushButton_open_image.setDefault(True)
        self.pushButton_open_image.setObjectName("pushButton_open_image")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 250, 191, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_classic = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_classic.setGeometry(QtCore.QRect(50, 30, 93, 28))
        self.pushButton_classic.setObjectName("pushButton_classic")
        self.textBrowser_result = QtWidgets.QTextBrowser(Form)
        self.textBrowser_result.setGeometry(QtCore.QRect(130, 410, 111, 31))
        self.textBrowser_result.setObjectName("textBrowser_result")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 420, 54, 12))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_image_1.setText(_translate("Form", "分类图"))
        self.pushButton_open_image.setText(_translate("Form", "打开图片"))
        self.groupBox_3.setTitle(_translate("Form", "经典神经网络模型"))
        self.pushButton_classic.setText(_translate("Form", "分类"))
        self.label.setText(_translate("Form", "分类结果"))
