from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1215, 940)
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setGeometry(QtCore.QRect(240, 60, 900, 700))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image.setFont(font)
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.pushButton_open_image = QtWidgets.QPushButton(Form)
        self.pushButton_open_image.setGeometry(QtCore.QRect(20, 20, 191, 28))
        self.pushButton_open_image.setCheckable(False)
        self.pushButton_open_image.setDefault(True)
        self.pushButton_open_image.setObjectName("pushButton_open_image")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 211, 191))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 151, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_zoom_factor_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_zoom_factor_1.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_zoom_factor_1.setFont(font)
        self.label_zoom_factor_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zoom_factor_1.setObjectName("label_zoom_factor_1")
        self.horizontalLayout.addWidget(self.label_zoom_factor_1)
        self.label_zoom_factor_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_zoom_factor_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.label_zoom_factor_2.setFont(font)
        self.label_zoom_factor_2.setText("")
        self.label_zoom_factor_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zoom_factor_2.setObjectName("label_zoom_factor_2")
        self.horizontalLayout.addWidget(self.label_zoom_factor_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_zoom_in = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_zoom_in.setObjectName("pushButton_zoom_in")
        self.verticalLayout.addWidget(self.pushButton_zoom_in)
        self.pushButton_zoom_out = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_zoom_out.setObjectName("pushButton_zoom_out")
        self.verticalLayout.addWidget(self.pushButton_zoom_out)
        self.pushButton_zoom_reset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_zoom_reset.setObjectName("pushButton_zoom_reset")
        self.verticalLayout.addWidget(self.pushButton_zoom_reset)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 320, 211, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 191, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_srcImage_size = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_srcImage_size.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_srcImage_size.setFont(font)
        self.label_srcImage_size.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_srcImage_size.setObjectName("label_srcImage_size")
        self.verticalLayout_2.addWidget(self.label_srcImage_size)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_5.addWidget(self.label_1)
        self.spinBox_anchor_x = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_anchor_x.setMaximum(99)
        self.spinBox_anchor_x.setObjectName("spinBox_anchor_x")
        self.horizontalLayout_5.addWidget(self.spinBox_anchor_x)
        self.spinBox_anchor_y = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_anchor_y.setMaximum(99)
        self.spinBox_anchor_y.setObjectName("spinBox_anchor_y")
        self.horizontalLayout_5.addWidget(self.spinBox_anchor_y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinBox_X_offset = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_X_offset.setMaximum(99)
        self.spinBox_X_offset.setObjectName("spinBox_X_offset")
        self.horizontalLayout_4.addWidget(self.spinBox_X_offset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_left_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_left_2.setFont(font)
        self.label_left_2.setObjectName("label_left_2")
        self.horizontalLayout_2.addWidget(self.label_left_2)
        self.spinBox_Y_offset = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_Y_offset.setObjectName("spinBox_Y_offset")
        self.horizontalLayout_2.addWidget(self.spinBox_Y_offset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pushButton_screenshot = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_screenshot.setGeometry(QtCore.QRect(20, 200, 171, 28))
        self.pushButton_screenshot.setObjectName("pushButton_screenshot")
        self.pushButton_save_file = QtWidgets.QPushButton(Form)
        self.pushButton_save_file.setGeometry(QtCore.QRect(20, 60, 191, 28))
        self.pushButton_save_file.setCheckable(False)
        self.pushButton_save_file.setDefault(True)
        self.pushButton_save_file.setObjectName("pushButton_save_file")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 590, 211, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 151, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_spin = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_spin.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_spin.setFont(font)
        self.label_spin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spin.setObjectName("label_spin")
        self.horizontalLayout_3.addWidget(self.label_spin)
        self.spinBox_spin = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_spin.setRange(0,360)
        self.spinBox_spin.setObjectName("spinBox_spin")
        self.horizontalLayout_3.addWidget(self.spinBox_spin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.pushButton_spin = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_spin.setObjectName("pushButton_spin")
        self.verticalLayout_3.addWidget(self.pushButton_spin)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 780, 211, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 20, 139, 100))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_updownX = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_updownX.setObjectName("pushButton_updownX")
        self.verticalLayout_5.addWidget(self.pushButton_updownX)
        self.pushButton_updownY = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_updownY.setObjectName("pushButton_updownY")
        self.verticalLayout_5.addWidget(self.pushButton_updownY)
        self.pushButton_updownXY = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_updownXY.setObjectName("pushButton_updownXY")
        self.verticalLayout_5.addWidget(self.pushButton_updownXY)

        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(260, 790, 117, 133))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.spinBox_02 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_02.setObjectName("spinBox_02")

        self.horizontalLayout_8.addWidget(self.spinBox_02)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.spinBox_12 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_12.setObjectName("spinBox_12")
        self.horizontalLayout_9.addWidget(self.spinBox_12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.pushButton_move = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_move.setObjectName("pushButton_move")
        self.verticalLayout_6.addWidget(self.pushButton_move)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图像几何变换"))
        self.label_image.setText(_translate("Form", "图片显示区"))
        self.pushButton_open_image.setText(_translate("Form", "打开图片"))
        self.groupBox.setTitle(_translate("Form", "缩放控制"))
        self.label_zoom_factor_1.setText(_translate("Form", "缩放系数："))
        self.pushButton_zoom_in.setText(_translate("Form", "放大"))
        self.pushButton_zoom_out.setText(_translate("Form", "缩小"))
        self.pushButton_zoom_reset.setText(_translate("Form", "默认大小"))
        self.groupBox_2.setTitle(_translate("Form", "裁切控制"))
        self.label_srcImage_size.setText(_translate("Form", "原图X轴*Y轴："))
        self.label_1.setText(_translate("Form", "锚点坐标"))
        self.label_2.setText(_translate("Form", "X轴偏移"))
        self.label_left_2.setText(_translate("Form", "Y轴偏移"))
        self.pushButton_screenshot.setText(_translate("Form", "图片裁切"))
        self.pushButton_save_file.setText(_translate("Form", "保存图片"))
        self.groupBox_3.setTitle(_translate("Form", "旋转控制"))
        self.label_spin.setText(_translate("Form", "绕中心点旋转"))
        self.pushButton_spin.setText(_translate("Form", "旋转"))
        self.groupBox_4.setTitle(_translate("Form", "翻转控制"))
        self.pushButton_updownX.setText(_translate("Form", "以X轴为对称轴翻转"))
        self.pushButton_updownY.setText(_translate("Form", "以Y轴为对称轴翻转"))
        self.pushButton_updownXY.setText(_translate("Form", "X轴、Y轴同时翻转"))
        self.groupBox_5.setTitle(_translate("Form", "平移控制"))
        self.label.setText(_translate("Form", "M(02)"))
        self.label_4.setText(_translate("Form", "M(12)"))
        self.pushButton_move.setText(_translate("Form", "平移"))

